modLoader = "${rootProject.name}"
loaderVersion = "[${modVersion},)"
license = "${modLicense}"

[[mods]]
modId = "${rootProject.name}${project.name}"
version = "${modVersion}"
displayName = "${modDisplayName}"
description = "${modDescription}"
logoFile = "logo.png"
authors = "${modAuthors}"
displayTest = "NONE"

[[dependencies.${rootProject.name}${project.name}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"
